# package model.dynamics.potential
_target_: src.models.components.spectral_onsagernet_2d.potential.allen_cahn.AllenCahnPotential
Lx: 6.283185307179586 # 2π
Ly: 6.283185307179586 # 2π
Nx: 128
Ny: 128
